Repository Wanted-Pre-Onboarding-Android-Team-3/android-wanted-LocationHistoryApp, pull requests merged in 2022-09, with the labels that each got.

#6 [FEAT] 네이버 맵 기초 세팅
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/preonboarding/locationhistory/WantedApplication.kt
  app/src/main/java/com/preonboarding/locationhistory/common/Constants.kt
  app/src/main/java/com/preonboarding/locationhistory/presentation/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle.properties
  settings.gradle
Labels: chore, DONE, feature, 재성 :unicorn:

#5 [FEAT] Room DB,DAO,Item 추가 및 HistoryDialog 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/preonboarding/locationhistory/data/History.kt
  app/src/main/java/com/preonboarding/locationhistory/data/HistoryDB.kt
  app/src/main/java/com/preonboarding/locationhistory/data/HistoryDao.kt
  app/src/main/java/com/preonboarding/locationhistory/presentation/HistoryDialogAdapter.kt
  app/src/main/java/com/preonboarding/locationhistory/presentation/HistoryDialogViewModel.kt
  app/src/main/res/drawable/bg_dialog_border_1.xml
  app/src/main/res/drawable/bg_dialog_radius_20.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_history.xml
  app/src/main/res/layout/item_history.xml
  app/src/main/res/values/strings.xml
Labels: DONE, feature, 준성 :unicorn:

#11 [ADD] location permission check ( >= android M )
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/preonboarding/locationhistory/presentation/MainActivity.kt
Labels: feature, IN PROGRESS, 인아 :unicorn:

#12 [UPDATE] location permission check ( >= android M )
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/preonboarding/locationhistory/presentation/MainActivity.kt
Labels: feature, IN PROGRESS, 인아 :unicorn:

#14 [FEAT] 사용자 현재 위치 받아오기 및 마커 찍기
  app/build.gradle
  app/src/main/java/com/preonboarding/locationhistory/common/Constants.kt
  app/src/main/java/com/preonboarding/locationhistory/presentation/MainActivity.kt
Labels: DONE, feature, 재성 :unicorn:

#17 [FEAT] #15 설정 Dialog 구현
  app/src/main/java/com/preonboarding/locationhistory/WantedApplication.kt
  app/src/main/java/com/preonboarding/locationhistory/common/Constants.kt
  app/src/main/java/com/preonboarding/locationhistory/presentation/MainActivity.kt
  app/src/main/java/com/preonboarding/locationhistory/util/AnimationUtil.kt
  app/src/main/java/com/preonboarding/locationhistory/util/PreferencesUtil.kt
  app/src/main/res/anim/cycle_3.xml
  app/src/main/res/anim/shake.xml
  app/src/main/res/drawable/bg_white_radius_5.xml
  app/src/main/res/layout/dialog_save_history_settings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: DONE, feature, ui, resource

#19 [REFACTOR] #18 현재 위치 좌표 함수 분리
  app/src/main/java/com/preonboarding/locationhistory/presentation/MainActivity.kt
Labels: DONE, refactor, 재성 :unicorn:

#22 [UPDATE] #10 location and background permission 확인 구현
  app/src/main/java/com/preonboarding/locationhistory/presentation/MainActivity.kt
Labels: DONE, feature, 인아 :unicorn:

#23 [FIX] getLastLocation Null 대응
  app/src/main/java/com/preonboarding/locationhistory/presentation/MainActivity.kt
  app/src/main/java/com/preonboarding/locationhistory/util/LocationUtil.kt
Labels: DONE, fix, 재성 :unicorn:

#25 [FEAT] 주소 다이얼로그 구현
  app/src/main/java/com/preonboarding/locationhistory/common/util/DialogUtil.kt
  app/src/main/java/com/preonboarding/locationhistory/presentation/MainActivity.kt
  app/src/main/res/layout/dialog_address.xml
Labels: DONE, feature, 재성 :unicorn:

#28 [ADD] check permission in on resume
  app/src/main/java/com/preonboarding/locationhistory/presentation/MainActivity.kt
Labels: 인아 :unicorn:

#20 Feat/9 dialog
  app/build.gradle
  app/src/main/java/com/preonboarding/locationhistory/data/History.kt
  app/src/main/java/com/preonboarding/locationhistory/data/HistoryDB.kt
  app/src/main/java/com/preonboarding/locationhistory/data/HistoryDao.kt
  app/src/main/java/com/preonboarding/locationhistory/data/HistoryRepository.kt
  app/src/main/java/com/preonboarding/locationhistory/data/HistoryRepositoryImpl.kt
  app/src/main/java/com/preonboarding/locationhistory/presentation/HistoryDialogAdapter.kt
  app/src/main/java/com/preonboarding/locationhistory/presentation/HistoryDialogViewModel.kt
  app/src/main/java/com/preonboarding/locationhistory/presentation/HistoryDialogViewModelFactory.kt
  app/src/main/java/com/preonboarding/locationhistory/presentation/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_history.xml
  app/src/main/res/layout/item_history.xml
Labels: DONE, feature, ui, 준성 :unicorn:

#29 [FEAT] #3 History 저장 구현
  app/src/main/java/com/preonboarding/locationhistory/common/Constants.kt
  app/src/main/java/com/preonboarding/locationhistory/presentation/MainActivity.kt
  app/src/main/java/com/preonboarding/locationhistory/presentation/SaveHistoryWorker.kt
  app/src/main/java/com/preonboarding/locationhistory/util/AnimationUtil.kt
  app/src/main/java/com/preonboarding/locationhistory/util/LocationUtil.kt
  app/src/main/java/com/preonboarding/locationhistory/util/PreferencesUtil.kt
  app/src/main/java/com/preonboarding/locationhistory/util/WorkMangerUtil.kt
  app/src/main/res/layout/activity_main.xml
Labels: feature, fix, IN PROGRESS, 영진 :unicorn:

#31 [FEAT] History 수정 0925 #9
  app/src/main/java/com/preonboarding/locationhistory/presentation/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: feature, fix, 준성 :unicorn:
